const product = [
  {
    id: 1,
    name: "Men's Leather Jacket",
    price: 129.99,
    rating: 4.6,
    description:
      "Premium genuine leather jacket with a stylish fit and durable design.",
    category: "Clothing",
    brand: "Zara",
    image: ["https://cdn.pixabay.com/photo/2016/11/29/01/34/man-1866572_1280.jpg"],
    stock: 25,
    color: "Black",
    size: ["S", "M", "L", "XL"],
    material: "Genuine Leather",
    warranty: "6 Months",
    features: ["Slim Fit", "Zipper Closure", "Inner Pocket"],
    reviews: 150,
  },
  {
    id: 2,
    name: "Women's Handbag",
    price: 79.99,
    rating: 4.7,
    description:
      "Elegant and spacious handbag made from high-quality faux leather.",
    category: "Accessories",
    brand: "Michael Kors",
    image: ["https://cdn.pixabay.com/photo/2017/08/20/11/39/handbag-2661412_1280.jpg"],
    stock: 40,
    color: "Beige",
    material: "Faux Leather",
    warranty: "1 Year",
    features: ["Multiple Compartments", "Adjustable Strap", "Gold-tone Hardware"],
    reviews: 220,
  },
  {
    id: 3,
    name: "Unisex Sunglasses",
    price: 49.99,
    rating: 4.5,
    description:
      "Classic aviator sunglasses with UV400 protection and polarized lenses.",
    category: "Accessories",
    brand: "Ray-Ban",
    image: "https://cdn.pixabay.com/photo/2020/03/02/11/52/accessory-4895500_1280.jpg",
    stock: 100,
    color: "Silver Frame, Black Lens",
    material: "Metal & Polycarbonate",
    warranty: "1 Year",
    features: ["UV400 Protection", "Scratch Resistant", "Lightweight Design"],
    reviews: 300,
  },
  {
    id: 4,
    name: "Men's Sports Sneakers",
    price: 99.99,
    rating: 4.8,
    description:
      "Comfortable and stylish sports sneakers with breathable fabric and cushioned sole.",
    category: "Clothing",
    brand: "Nike",
    image: "https://cdn.pixabay.com/photo/2020/04/09/08/38/nike-5020361_1280.jpg",
    stock: 60,
    color: "White & Black",
    size: [7, 8, 9, 10, 11],
    material: "Mesh & Rubber",
    warranty: "6 Months",
    features: ["Lightweight", "Non-Slip Sole", "Arch Support"],
    reviews: 180,
  },
];

export default product;
